//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacilityClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://DefaultNamespace", ConfigurationName="ServiceReference1.LocalServer")]
    public interface LocalServer {
        
        // CODEGEN: Generating message contract since element name vin from namespace http://DefaultNamespace is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        FacilityClient.ServiceReference1.registerCarResponse registerCar(FacilityClient.ServiceReference1.registerCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FacilityClient.ServiceReference1.registerCarResponse> registerCarAsync(FacilityClient.ServiceReference1.registerCarRequest request);
        
        // CODEGEN: Generating message contract since element name carVin from namespace http://DefaultNamespace is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        FacilityClient.ServiceReference1.trackPartResponse trackPart(FacilityClient.ServiceReference1.trackPartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FacilityClient.ServiceReference1.trackPartResponse> trackPartAsync(FacilityClient.ServiceReference1.trackPartRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerCar", Namespace="http://DefaultNamespace", Order=0)]
        public FacilityClient.ServiceReference1.registerCarRequestBody Body;
        
        public registerCarRequest() {
        }
        
        public registerCarRequest(FacilityClient.ServiceReference1.registerCarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DefaultNamespace")]
    public partial class registerCarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string model;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string make;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int year;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double weight;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string parts;
        
        public registerCarRequestBody() {
        }
        
        public registerCarRequestBody(string vin, string model, string make, int year, double weight, string parts) {
            this.vin = vin;
            this.model = model;
            this.make = make;
            this.year = year;
            this.weight = weight;
            this.parts = parts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerCarResponse", Namespace="http://DefaultNamespace", Order=0)]
        public FacilityClient.ServiceReference1.registerCarResponseBody Body;
        
        public registerCarResponse() {
        }
        
        public registerCarResponse(FacilityClient.ServiceReference1.registerCarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DefaultNamespace")]
    public partial class registerCarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool registerCarReturn;
        
        public registerCarResponseBody() {
        }
        
        public registerCarResponseBody(bool registerCarReturn) {
            this.registerCarReturn = registerCarReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class trackPartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="trackPart", Namespace="http://DefaultNamespace", Order=0)]
        public FacilityClient.ServiceReference1.trackPartRequestBody Body;
        
        public trackPartRequest() {
        }
        
        public trackPartRequest(FacilityClient.ServiceReference1.trackPartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DefaultNamespace")]
    public partial class trackPartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string carVin;
        
        public trackPartRequestBody() {
        }
        
        public trackPartRequestBody(string carVin) {
            this.carVin = carVin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class trackPartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="trackPartResponse", Namespace="http://DefaultNamespace", Order=0)]
        public FacilityClient.ServiceReference1.trackPartResponseBody Body;
        
        public trackPartResponse() {
        }
        
        public trackPartResponse(FacilityClient.ServiceReference1.trackPartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DefaultNamespace")]
    public partial class trackPartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string trackPartReturn;
        
        public trackPartResponseBody() {
        }
        
        public trackPartResponseBody(string trackPartReturn) {
            this.trackPartReturn = trackPartReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LocalServerChannel : FacilityClient.ServiceReference1.LocalServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocalServerClient : System.ServiceModel.ClientBase<FacilityClient.ServiceReference1.LocalServer>, FacilityClient.ServiceReference1.LocalServer {
        
        public LocalServerClient() {
        }
        
        public LocalServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocalServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FacilityClient.ServiceReference1.registerCarResponse FacilityClient.ServiceReference1.LocalServer.registerCar(FacilityClient.ServiceReference1.registerCarRequest request) {
            return base.Channel.registerCar(request);
        }
        
        public bool registerCar(string vin, string model, string make, int year, double weight, string parts) {
            FacilityClient.ServiceReference1.registerCarRequest inValue = new FacilityClient.ServiceReference1.registerCarRequest();
            inValue.Body = new FacilityClient.ServiceReference1.registerCarRequestBody();
            inValue.Body.vin = vin;
            inValue.Body.model = model;
            inValue.Body.make = make;
            inValue.Body.year = year;
            inValue.Body.weight = weight;
            inValue.Body.parts = parts;
            FacilityClient.ServiceReference1.registerCarResponse retVal = ((FacilityClient.ServiceReference1.LocalServer)(this)).registerCar(inValue);
            return retVal.Body.registerCarReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FacilityClient.ServiceReference1.registerCarResponse> FacilityClient.ServiceReference1.LocalServer.registerCarAsync(FacilityClient.ServiceReference1.registerCarRequest request) {
            return base.Channel.registerCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacilityClient.ServiceReference1.registerCarResponse> registerCarAsync(string vin, string model, string make, int year, double weight, string parts) {
            FacilityClient.ServiceReference1.registerCarRequest inValue = new FacilityClient.ServiceReference1.registerCarRequest();
            inValue.Body = new FacilityClient.ServiceReference1.registerCarRequestBody();
            inValue.Body.vin = vin;
            inValue.Body.model = model;
            inValue.Body.make = make;
            inValue.Body.year = year;
            inValue.Body.weight = weight;
            inValue.Body.parts = parts;
            return ((FacilityClient.ServiceReference1.LocalServer)(this)).registerCarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FacilityClient.ServiceReference1.trackPartResponse FacilityClient.ServiceReference1.LocalServer.trackPart(FacilityClient.ServiceReference1.trackPartRequest request) {
            return base.Channel.trackPart(request);
        }
        
        public string trackPart(string carVin) {
            FacilityClient.ServiceReference1.trackPartRequest inValue = new FacilityClient.ServiceReference1.trackPartRequest();
            inValue.Body = new FacilityClient.ServiceReference1.trackPartRequestBody();
            inValue.Body.carVin = carVin;
            FacilityClient.ServiceReference1.trackPartResponse retVal = ((FacilityClient.ServiceReference1.LocalServer)(this)).trackPart(inValue);
            return retVal.Body.trackPartReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FacilityClient.ServiceReference1.trackPartResponse> FacilityClient.ServiceReference1.LocalServer.trackPartAsync(FacilityClient.ServiceReference1.trackPartRequest request) {
            return base.Channel.trackPartAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacilityClient.ServiceReference1.trackPartResponse> trackPartAsync(string carVin) {
            FacilityClient.ServiceReference1.trackPartRequest inValue = new FacilityClient.ServiceReference1.trackPartRequest();
            inValue.Body = new FacilityClient.ServiceReference1.trackPartRequestBody();
            inValue.Body.carVin = carVin;
            return ((FacilityClient.ServiceReference1.LocalServer)(this)).trackPartAsync(inValue);
        }
    }
}
